### ISSUE TITLE
Link to annotation database is broken

### ISSUE THREAD

**Issue by ursky** [koszullab/metaTOR#6]
Dear developers, 

It looks like the link http://dl.pasteur.fr/fop/gzLz1lG8/hmm_databases.tgz is broken, at least from my location (US). Is it possible to have it updated so I can download the HMM model? Alternatively, can you direct me to the file I need to download to place and extract into `python3.7/site-packages/metator/bin/HMM_databases`?

**Comment by baudrly** [comment]
Hello, sorry for the link breakage, it was meant to be a temporary solution. I have set up LFS so that the databases are now [directly](https://github.com/koszullab/metaTOR/blob/master/metator/data/hmm_databases.tgz?raw=true) stored on the repo. The URL in ```metator.sh``` has also been updated accordingly. Please let me know if you're having issues downloading/extracting the file.

**Comment by ABignaud** [comment]
Hi,

I have reupload the hmm database which was missing. It's available at this link: https://github.com/koszullab/metaTOR/raw/master/metator/data/hmm_databases.tgz.

Best,
